# Generated by Django 3.2.6 on 2021-10-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_liked_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='pic',
            field=models.ImageField(null=True, upload_to='profile_pic/%y'),
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
