# Generated by Django 3.2.6 on 2021-10-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211004_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bgpic',
            field=models.ImageField(null=True, upload_to='bg_pic/%y'),
        ),
    ]
