# Generated by Django 3.2.6 on 2021-10-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_person_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pic',
            field=models.ImageField(null=True, upload_to='profile_pic/%y'),
        ),
    ]
